// <auto-generated />
using System;
using ComposerCMS.Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ComposerCMS.Core.Migrations
{
    [DbContext(typeof(ComposerCMSContext))]
    [Migration("20200813011019_DatabaseV1")]
    partial class DatabaseV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ComposerCMS.Core.Entity.ActivityHistory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("character varying(16)")
                        .HasMaxLength(16);

                    b.Property<string>("Data")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Entity")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("Action");

                    b.HasIndex("DateAdded");

                    b.HasIndex("Entity");

                    b.HasIndex("UserIDAdded");

                    b.ToTable("ActivityHistory");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Blog", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.ExternalResource", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("Href")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("ExternalResource");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Layout", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Layout");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.LayoutScript", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ExternalResourceID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LayoutID")
                        .HasColumnType("uuid");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("LayoutScript");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Menu", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.MenuItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayText")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("MenuID")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RouteID")
                        .HasColumnType("uuid")
                        .HasMaxLength(256);

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("RouteID");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Page", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateLastPublished")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAbstract")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemPage")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceVersionID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DateAdded");

                    b.HasIndex("Name");

                    b.HasIndex("Path");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.PageScript", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ExternalResourceID")
                        .HasColumnType("uuid");

                    b.Property<int>("LoadOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("PageID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("PageScript");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.PageVersion", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("PageID")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("DateAdded");

                    b.HasIndex("Name");

                    b.HasIndex("PageID");

                    b.HasIndex("Path");

                    b.ToTable("PageVersion");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Post", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlogID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateLastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("character varying(512)")
                        .HasMaxLength(512);

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.HasIndex("IsPinned");

                    b.HasIndex("IsPublic");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Title");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Route", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EntityID")
                        .HasColumnType("text");

                    b.Property<string>("OriginalEntityText")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDAdded")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("ComposerCMS.Core.Entity.Settings", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefaultRouteID")
                        .HasColumnType("uuid");

                    b.Property<bool>("MinimizeCss")
                        .HasColumnType("boolean");

                    b.Property<bool>("MinimizeJs")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ThemeKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid>("UserIDLastUpdated")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "993ab932-df4d-47ba-902f-2ec313dc4e73",
                            ConcurrencyStamp = "39a07760-467b-45a5-a10b-e8ad62ba7891",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4d323c3f-d805-4932-bb1e-02cc2d0f58b5",
                            ConcurrencyStamp = "9e6ac746-7822-4e4e-b901-2ca2a399c82e",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "de6f9df8-d8ef-4dc4-b0b0-fc2dc2c51aed",
                            ConcurrencyStamp = "0253e128-d143-4847-80ad-87ed7741b80a",
                            Name = "Author",
                            NormalizedName = "AUTHOR"
                        },
                        new
                        {
                            Id = "a7f52a41-4c4c-45e0-9088-a89cb25dea92",
                            ConcurrencyStamp = "da7074dc-e93d-4c14-89d9-6a406d8f4df8",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        },
                        new
                        {
                            Id = "e3c7b0e0-88f7-4bd0-b846-66c63db1f614",
                            ConcurrencyStamp = "44541a68-843e-4ed6-bfc5-b095a294212b",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "de0fa044-1d5b-44d7-a93e-66598b2b7c84",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db77a034-0d81-48b2-b236-4f5fe8a786ce",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEOGx0PnjKOLI97oMyt2Mzr7dh0dnzLYezNqzTnCCOz173aT0/zOyVfI8mg91gMXjVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3df9946f-18e9-4c48-9a04-fc2cdd2ee239",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "de0fa044-1d5b-44d7-a93e-66598b2b7c84",
                            RoleId = "993ab932-df4d-47ba-902f-2ec313dc4e73"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
